service-name: "test-app"
stream-router:
  booking:
    bootstrap-servers: "localhost:9094"
    instance-count: 4
    # how many consumers to spawn.
    # adjust this number to the number of partitions
    # to maximize parallelization
    origin-topics: "^.*-message-log"
    group-id: "message_log_go"
  test-entity:
    bootstrap-servers: "localhost:9092"
    instance-count: 2
    origin-topics: "test-topic2"
    group-id: "test-group2"
  json-entity:
    bootstrap-servers: "localhost:9092"
    instance-count: 1
    origin-topics: "json-test"
    group-id: "json-group"
log-level: "debug"
retry:
  enabled: true
  count: 5
rabbitmq:
  host: "amqp://user:bitnami@localhost:5672/"
  delay-queue-expiration: "1000"
statsd:
  host: "localhost:8125"
http-server:
  port: 8080
