stream-router:
  - topic-entity: "test-entity2"
    bootstrap-servers: "localhost:9092"
    instance-count: 2
    origin-topics: "topic1"
    groupID: "test-group"
  - topic-entity: "test-entity"
    bootstrap-servers: "localhost:9092"
    instance-count: 2
    origin-topics: "topic2"
    groupID: "test-group2"

