name: GoCI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Build
        run: go build -v ./...

      - name: Test
        run: make lib.test

      - name: Test Integration
        run: make lib.test-integration

      - name: Coverage
        run: |
          make docker.start
          sleep 30
          make lib.test-coverage

      - name: Upload Coverage
        uses: codecov/codecov-action@v1
        with:
          files: cp.out
