name: update-go-mod-template

on:
  workflow_dispatch:
    

jobs:
  update-template:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4

      - run: |
          git fetch --tags
          LATEST_TAG=$(git tag --sort=committerdate | tail -n1)
          sed -i -e "s/\(github.com\/gojekfarm\/ziggurat\) \(.*\)/\1 $LATEST_TAG/" cmd/templates/templates.go
          git config --global user.email 'github-actions@github.com'
          git config --global user.name 'github-actions'
          git commit -am "updates version in go.mod template"
          git push origin master
          git tag -f $LATEST_TAG $(git rev-parse HEAD)
          git push --force --tags
