name: update-pkg-cache

on:
  workflow_dispatch:

jobs:
  update-pkg-cache:
    runs-on: ubuntu-latest
    steps:
      - name: setup golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - uses: actions/checkout@v2.3.4

      - run: |
          git fetch --tags
          LATEST_TAG=$(git tag --sort=committerdate | tail -n1)
          GOPROXY=https://proxy.golang.org GO111MODULE=on
          cd ~/
          go get github.com/gojekfarm/ziggurat@$LATEST_TAG